### ISSUE TITLE
Separate traffic with a local port?

### ISSUE THREAD

**Issue by userisuserisuser** [KaringX/karing-ruleset#11]
Is it possible to override rulesets and redirect traffic through Karing with a local port?  i.e. 192.168.1.1:1234

**Comment by userisuserisuser** [comment]
Found a solution, leaving it here for googlers:

Enable "Syetem Proxy" and "Global" under it. Now you can pass your traffic to Karing through 127..0.0.1:3067 for HTTP(S) and Socks(4 and 5 but I seem to get better speed with 5).

I still don't know why this works though, I think UI needs some edit or have some explanation of settings, can't find them in FAQ or Tutorials.

What I initially thought was System Proxy is directing all the internet traffic through a system-wide proxy you set for your phone/etc, but apparently its the opposite.

Also the Rule/Global button under it, I thought "Rule" means to use the defined rulesets and "Global" means to override it, which is also not the case.

**Comment by GooRingX** [comment]
Global/rules are for traffic out of the proxy, not traffic into the proxy. Traffic into the proxy is controlled by the system proxy or TUN (virtual network card).
