### ISSUE TITLE
How to access Microsoft service without error?

### ISSUE THREAD

**Issue by alexlii1971** [KaringX/karing-ruleset#12]
Hello,

I am in China, and I have difficulties to access Microsoft service, like Bing, Outlook Email, copilot.

Microsoft service does not allow connection by VPN, otherwise it might show the errors when accessing Outlook.com,  the screenshot:

https://prnt.sc/U0Ds2gbSrpZJ

For copilot at https://copilot.microsoft.com/, it shows:

https://prnt.sc/VPN7qBpaX47y

**This page contains the following errors:
error on line 1 at column 1: Start tag expected, '<' not found
Below is a rendering of the page up to the first error.**

For Bing.com , it might show:
**An error (502 Bad Gateway) has occurred in response to this request.**

I understand that Outlook.com, bing could be accessed without VPN connections, because these services are open to China without limits.

However, copilot seems limited to access in China, and it always show errors if I use VPN.

Anyway to fix the issues please? 

Thanks

**Comment by GooRingX** [comment]
从所提供的信息中无法判断此问题是有karing引起
