### ISSUE TITLE
规则无法命中的问题

### ISSUE THREAD

**Issue by cvpas** [KaringX/karing-ruleset#5]
查看[chinaip.json](https://github.com/KaringX/karing-ruleset/blob/sing/ACL4SSR/ChinaIp.json)文件中的内容，得出结论39.107.194.137属于39.104.0.0/14，故该ip应该命中chinaip规则集。这个ip对应的域名是xylink.com,而访问该网站发现还是走了代理。疑惑不解,请大佬释疑，感激不尽。好多类似的网站也有一样的行为。
<img width="1412" alt="截屏2024-08-17 00 08 06" src="https://github.com/user-attachments/assets/7f0c7b46-3717-447f-afb5-95b9373b35de">
我的[配置文件](https://github.com/shallbytwo/sing-box/blob/main/config.json)

**Comment by GooRingX** [comment]
下载安装最新版本再试试

**Comment by cvpas** [comment]
> 下载安装最新版本再试试

早解决了，是嗅探复写的原因。谢谢
